### ISSUE TITLE
Screen Sharing Produces An Infinite Number Of Images

### ISSUE THREAD

**Issue by adebayoileri** [nexmo-community/screenshare-video-chat#1] opened 2020-12-30 15:33 UTC
Note:
This issue is part of my Vonage Voyagers application process

Background
On activating the screen sharing feature, the number of images formed on the screen is at infinite and could be solved by not displaying the screen of the sharer on the application page.

Image
![Screenshot (11)](https://user-images.githubusercontent.com/46798106/103363816-61cc0600-4abc-11eb-8765-e89d9e206568.png)

**Comment by phazonoverload** [comment] 2021-01-05 14:39
Thanks for this @adebayoileri. When you shared your screen you were given the option to share a whole screen, an application, or a single tab. If you chose to share content that includes the application you're building, this is completely expected behavior, and therefore not a bug. You'll find the same behavior in any application that supports screen sharing.

As part of the application to the Vonage Voyagers program, we ask you to identify and report a bug, or a suggested improvement to a repo. I'm going to close this issue and pop your application on hold. If you still want to be a part of the program, please open an issue which better answers the exercise in the next couple of weeks. If you have questions fire them over to voyagers@vonage.com - thanks!

**Closed as completed by phazonoverload** 2021-01-05 14:39 UTC

**Comment by adebayoileri** [comment] 2021-01-05 14:55
Okay Thanks, @phazonoverload.

**Comment by phazonoverload** [comment] 2021-01-25 11:14
Just checking in on this. The issue doesn't have to be on this repo, but we won't be able to progress your application without a completed and accepted exercise. If you have any questions let me know here or at kevin.lewis@vonage.com
